spring:
  application:
    name: myteam01
  mvc:
   view:
    prefix: /jsp/
    suffix: .jsp
  security:
    user:
      name: admin
      password: admin
  servlet:
    jsp:
      init-parameters:
        development: true
myuser:
  spring:
    datasource:
      hikari: 
        maximum-pool-size: 20
        minimum-idle: 5
        max-lifetime: 2
        auto-commit: false
        idle-timeout: 30000
        connection-timeout: 30000
        driver-class-name: oracle.jdbc.OracleDriver
        jdbc-url: jdbc:oracle:thin:@195.168.9.58:1521:xe
        username: teampj
        password: teampj
        pool-name: teampjCP	
springdoc:
  api-docs:
    enabled: true 
    version: openapi-3-0 #사용하는 버전을 명시
    packagesToScan: mokindang.jubging #api-docs 의 스캔 범위를 지정
    path: /v3/api-docs #api 문서 확인 경로, localhost:8080/v3/api-docs 로 접근

  default-consumes-media-type: application/json #기본으로 설정되는 미디어타입 지정
  auto-tag-classes: true #오토 태그 기능 활성화
  groups:
    enabled: false #api 그룹 기능, default는 true 이나 당장 사용하지 않기에 false 로 지정

  swagger-ui:
    operationsSorter: method #method 기준으로 정렬, 그외 alpha 로 정렬 가능
    path: /swagger-ui.html #swagger ui 의 api 문서 확인 경로 defalut 는 /swagger-ui.html 이다.


mybatis:
  mapper-locations: 
    - classpath:mapper/*.xml
  type-aliases-package: com.teamproject.myteam01.domain

logging:
  level:
    org.springframework.security: DEBUG		